# Generated by Django 6.0 on 2026-01-04 13:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('room_type', models.CharField(choices=[('general', 'Обычный класс'), ('lab', 'Лаборатория'), ('gym', 'Спортзал')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('day', models.CharField(choices=[('Monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница')], max_length=20)),
                ('slot', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('grade', models.CharField(max_length=10)),
                ('color', models.CharField(choices=[('indigo', 'Индиго'), ('blue', 'Синий'), ('green', 'Зеленый'), ('amber', 'Янтарный'), ('rose', 'Роза'), ('cyan', 'Голубой'), ('emerald', 'Изумруд'), ('violet', 'Фиолетовый')], default='indigo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.teacher')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['day', 'slot'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'day', 'slot'), name='unique_teacher_schedule'), models.UniqueConstraint(fields=('room', 'day', 'slot'), name='unique_room_schedule')],
            },
        ),
    ]
