# Generated by Django 6.0 on 2026-01-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lesson',
            name='unique_teacher_schedule',
        ),
        migrations.RemoveConstraint(
            model_name='lesson',
            name='unique_room_schedule',
        ),
    ]
